### ISSUE TITLE
could not find file with rosidl_cmakeConfig.cmake

### ISSUE THREAD

**Issue by applekrunch** [ros2-java/ros2_java#104]
Hi, when i try to build the file i keep having this error 

![Screenshot from 2020-04-09 10-54-30](https://user-images.githubusercontent.com/63383366/78853080-9c829f80-7a50-11ea-887a-a50fe2fe4eaa.png)
is there something that i need to add into the repo file or download?

**Comment by jacobperron** [comment]
Please try the updated instructions on the `main` branch with ROS Galactic. If you run into any problems, please open a ticket with steps to reproduce, thanks!
