### ISSUE TITLE
Build error on Windows 10 with Visual Studio 2019

### ISSUE THREAD

**Issue by mefoster** [ros2-java/ros2_java#113]
I have installed ROS 2 on my Windows 10 machine and have downloaded the latest ros2-java (checked out everything with vcs)

I am trying to build as follows:
`C:\dev\ament_ws>python src/ament/ament_tools/scripts/ament.py build
`
I get the following error (horizontal lines removed because they mess with markdown):

```
Process package 'ament_cmake_core' with context:
 source_space => C:\dev\ament_ws\src\ament\ament_cmake\ament_cmake_core
  build_space => C:\dev\ament_ws\build\ament_cmake_core
install_space => C:\dev\ament_ws\install
   make_flags => -j8, -l8
  build_tests => False
+++ Building 'ament_cmake_core'
ament build: Unknown / unsupported VS version: 16.0
```

Any suggestions on where to fix this?

**Comment by mefoster** [comment]
Have been trying to get this to work a bit more but I'm not an expert on Visual Studio or CMake so I'm heading down a rabbit hole. Has anyone actually ever built this successfully with Visual Studio 2019?

**Comment by esteve** [comment]
@mefoster thanks for trying out `ros2-java`. We're adding a CI workflow for Windows in https://github.com/ros2-java/ros2_java/pull/109 to make sure that `ros2-java` supports Windows. However, we're now targeting ROS 2 Dashing and Foxy in separately in non-master branches, and will soon update the `master` branch of `ros2-java`, which right now only supports ROS 2 Bouncy. What version of ROS 2 did you install?

**Comment by mefoster** [comment]
Foxy ... ah yes, now I see what might have happened. I'll look for the Foxy branch and try again.

**Comment by mefoster** [comment]
Right, I see that you opened a new request about describing how to build with colcon instead of ament. I was just in the process of discovering that ament is obsolete ... I'll stay tuned and try again when there are new instructions

**Comment by jacobperron** [comment]
I'm going to close this since we have this ticket to track getting CI turning over on Windows https://github.com/ros2-java/ros2_java/issues/102
