### ISSUE TITLE
[dashing] android build failure 

### ISSUE THREAD

**Issue by tal-grossman** [ros2-java/ros2_java#173]
going by the instructions `Download and Build ROS 2 Java for Android`
 in the dashing branch, the fastrtps pkg is failing.  I get this error msg while building:

```
--- stderr: fastrtps                                                                                                        
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindOpenSSL.cmake:390 (find_package_handle_standard_args)
  CMakeLists.txt:232 (find_package)


---
Failed   <<< fastrtps [0.53s, exited with code 1]

```

**additional information:**
- I used dashing docker
- android-ndk-r21
- environment variables were set accroding to the ndk and the sdk

I can see that according to the [CI](https://github.com/ros2-java/ros2_java/blob/dashing/.github/workflows/build_and_test.yml) the build is successful. I even tried doing according to that one and got the same result

**Comment by jacobperron** [comment]
I don't think CI on the `dashing` branch is complete for Android. Also, due to resource constraints our focus will be on supporting the latest available ROS distro (currently Galactic). Since Dashing is EOL, there is even more reason to upgrade :wink: 

Please checkout the `main` branch and report a new issue if you still run into problems.
