### ISSUE TITLE
Android 11 API 30 

### ISSUE THREAD

**Issue by ahmadnav** [ros2-java/ros2_java#176]
@esteve 
Are you guys having any issues with running or finding nodes on the newer androids?
On the s20 with android API 10 and and API >= 29 or Android 11 API 30 I seem to have silent issues detecting nodes i.e. there are no errors. I have the ROS_DOMAIN_ID set the same on android and laptop. Just curious if anyone has had this problem, seems to have worked fine with my older s9. I am running the dashing branch.

**Comment by ahmadnav** [comment]
Targetting API 29 works

**Comment by jtabraham123** [comment]
Did you ever get this to work on API 30 or higher?

**Comment by StevenNick88** [comment]
@ahmadnav  How do you set up ROS_DOMAIN_ID in Android？

**Comment by ahmadnav** [comment]
> @ahmadnav How do you set up ROS_DOMAIN_ID in Android？

Domain ID setup This is needed to discover android node from different machines with same domainid. I modified the code such that BaseComposableNode takes in parameter Domaid ID on the java side and carries it through to the createNode function.
domain id should be the same as ROS_DOMAIN_ID on the laptop or other machines.

RCLJava.java (231) add final int domain_id to createNode. Add domain_id to the nativeCreateNodeHandle(nodeName, namespace, domain_id, context.getHandle()); (232)
RCLJava.java (163) Modify private static native long nativeCreateNodeHandle(String nodeName, String namespace, int domain_id ,long contextHandle); to reflect above changes,

Add following function to RCLJava.java <--- this is called in BaseComposableNode
public static Node createNode(final String nodeName, final int domain_id) {
return createNode(nodeName, "", domain_id,RCLJava.getDefaultContext());
}


What you could do is modify Modify basecomposable node in BaseComposableNode.java BaseComposableNode(String name, int domain_id)  to either set a specific domain id or modify it from the java side via adding the domain_id in the jni calls

**Comment by StevenNick88** [comment]
您好，您的邮件已收到，感谢您的来信。祝您生活愉快！

**Comment by ahmadnav** [comment]
> Did you ever get this to work on API 30 or higher?

No sorry
