### ISSUE TITLE
Colcon build fails at rosidl_generator_java

### ISSUE THREAD

**Issue by 91fabbai91** [ros2-java/ros2_java#188]
I tried to compile the package with Ubuntu 20.04 ROS Foxy and did the things, which are mentioned at the README
In package rosidl_generator_java I got an error

Find attached my stacktrace:

`colcon build --symlink-install
[0.340s] WARNING:colcon.colcon_core.verb:No task extension to 'build' a 'ros.ament_gradle' package
Starting >>> ament_java_resources
Finished <<< ament_java_resources [0.10s]                   
Starting >>> ament_build_type_gradle
[0.617s] WARNING:colcon.colcon_ros.task.ament_python.build:Package 'ament_build_type_gradle' doesn't explicitly install a marker in the package index (colcon-ros currently does it implicitly but that fallback will be removed in the future)
[0.617s] WARNING:colcon.colcon_ros.task.ament_python.build:Package 'ament_build_type_gradle' doesn't explicitly install the 'package.xml' file (colcon-ros currently does it implicitly but that fallback will be removed in the future)
Finished <<< ament_build_type_gradle [0.52s]           
Starting >>> ament_cmake_export_jars
Starting >>> ament_cmake_export_jni_libraries
Finished <<< ament_cmake_export_jars [0.09s]                                   
Starting >>> rcljava_common
Finished <<< ament_cmake_export_jni_libraries [0.10s]
Finished <<< rcljava_common [0.12s]                   
Starting >>> rosidl_generator_java
--- stderr: rosidl_generator_java                          
CMake Error at /opt/ros/foxy/share/rosidl_typesupport_fastrtps_c/cmake/rosidl_typesupport_fastrtps_c_generate_interfaces.cmake:166 (add_dependencies):
  The dependency target "rosidl_generator_java__cpp" of target
  "rosidl_generator_java__rosidl_typesupport_fastrtps_c" does not exist.
Call Stack (most recent call first):
  /opt/ros/foxy/share/ament_cmake_core/cmake/core/ament_execute_extensions.cmake:48 (include)
  /opt/ros/foxy/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:286 (ament_execute_extensions)
  CMakeLists.txt:54 (rosidl_generate_interfaces)

CMake Error at /opt/ros/foxy/share/rosidl_typesupport_fastrtps_cpp/cmake/rosidl_typesupport_fastrtps_cpp_generate_interfaces.cmake:169 (add_dependencies):
  The dependency target "rosidl_generator_java__cpp" of target
  "rosidl_generator_java__rosidl_typesupport_fastrtps_cpp" does not exist.
Call Stack (most recent call first):
  /opt/ros/foxy/share/ament_cmake_core/cmake/core/ament_execute_extensions.cmake:48 (include)
  /opt/ros/foxy/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:286 (ament_execute_extensions)
  CMakeLists.txt:54 (rosidl_generate_interfaces)

CMake Generate step failed.  Build files cannot be regenerated correctly.
---
Failed   <<< rosidl_generator_java [0.97s, exited with code 1]

Summary: 5 packages finished [1.99s]
  1 package failed: rosidl_generator_java
  1 package had stderr output: rosidl_generator_java
  24 packages not processed
`

**Comment by jacobperron** [comment]
Due to resource limits, our plan for the ros2-java project is to only target the latest ROS release (currently, Galactic).
Since there are no plans for maintainers to look into Foxy support, I'm going to close this.

That being said, I'm happy to support any community effort to get this working for Foxy. I recommend trying the latest changes on the `main` branch and if that doesn't work you can try going back to an earlier commit (maybe this one: fe96b5e8cb375e2863ff13fe397ca95d9b9856ff).
