### ISSUE TITLE
Support for Android SDK 30+

### ISSUE THREAD

**Issue by jtabraham123** [ros2-java/ros2_java#225]
Hi, I am currently building an app that targets android sdk 30+ with ros2_java. However, for some reason I cannot get ros2 talker and listener nodes to communicate in sdk 30+. It works over wifi network in sdk 29 and below (I have followed example from https://github.com/YasuChiba/ros2-android-test-app). But in sdk 30, the talker and listener node can only communicate locally on the app and not over the network. Has anyone else had this issue with sdk 30+ and know a workaround?

**Comment by jtabraham123** [comment]
Note: One thing ive noticed when I run api 30+ (Android 11) vs 29 and below, the node handles and context handles are now all negative. They were positive in 29 and below. This would not be the issue if everything is cast properly though. I am just wondering if it could be a casting thing.

**Comment by jtabraham123** [comment]
I have a few ideas as to why this is happening, could be the middleware (in which case this issue would be better suited for one of those repos) or the socket layer.

**Comment by YasuChiba** [comment]
I'm wondering if this is the cause. (Though I have not tried yet)

https://github.com/eProsima/Fast-DDS/pull/2677

**Comment by jtabraham123** [comment]
Yes it is Thank you YasuChiba so much for pointing this out! Just had to update the repos file to Fast-DDS 2.8.0 (version with this commited) and Fast CDR to v1.0.25.
