### ISSUE TITLE
Windows CI build

### ISSUE THREAD

**Issue by calvertdw** [ros2-java/ros2_java#50]
@esteve If I remember correctly you said you had this project building with VSTS. I'm having errors building on my machine and want to compare with the CI, but I can't find a link to it anywhere.

If not, can we get an AppVeyor build going?

**Comment by esteve** [comment]
I've set Appveyor for Linux, but I'm happy to add a Windows job. Could you submit a PR for that? Thanks.

**Comment by calvertdw** [comment]
Will do! Thanks

**Comment by calvertdw** [comment]
I haven't forgotten about this. I've been busy with other stuff and I've never worked with AppVeyor before so I have to make time to get up to speed.

**Comment by esteve** [comment]
No worries! Thanks a lot for your contributions :-)

**Comment by jacobperron** [comment]
Duplicate of https://github.com/ros2-java/ros2_java/issues/102
