### ISSUE TITLE
Can not interrupt a running node with CTRL+C

### ISSUE THREAD

**Issue by arturrataj** [ros2-java/ros2_java#58]
I can not interrupt a node with CTRL+C if it waits on ros i/o with no message transmitted, e.g.

$ ros2 run rcljava_examples subscriber_lambda
^C^C

But this will in turn work:

$ ros2 run rcljava_examples subscriber_lambda
I heard: [Hello, world! 5]
I heard: [Hello, world! 6]
^Cterminate called after throwing an instance of 'std::system_error'

If you randomly terminate/run/pause nodes in the demo pair publisher/subscriber, you can also occasionally see on the publisher side:

^Cdouble free or corruption (fasttop)

**Comment by jacobperron** [comment]
I'm not sure that this issue still happens with the latest version of ROS 2 Java. Please try the `main` branch with ROS Galactic and report back if the issue persists.
