### ISSUE TITLE
unique_identifier_msgs is needed for action_msgs

### ISSUE THREAD

**Issue by cyrilleberger** [ros2-java/ros2_java#64]
I had an error when building action_msgs, I needed to add https://github.com/ros2/unique_identifier_msgs to my workspace. You would need to add it to your ros2_java_*.repos files

**Comment by charlotteheggem** [comment]
Hi, did you mangage to successfully build the repo? I tried to follow your steps, but get the following error message:
![action_msgs](https://user-images.githubusercontent.com/44672581/69635796-7afeb980-1055-11ea-9397-caca635d89e4.png)

I am using dashing.

**Comment by cyrilleberger** [comment]
Hi, no I gave up, it was too much effort for what I intended to do. I think ros2_java is currently dormant, the last commit is more than a year old.

**Comment by jacobperron** [comment]
FWIW, I've been working on reviving rcljava. I have a [Dockerfile](https://github.com/jacobperron/rcljava-docker/blob/e377aa100fc1f5a7bd7ec2a940c9e949693a3dc5/Dockerfile) with steps for compiling for Dashing. Currently,  it's using my own forks, but I think it would be nice to migrate the necessary repositories to the ros2 organization.

**Comment by esteve** [comment]
@jacobperron I'd rather keep ros2_java in its own organization, like rosjava. I created ros2-java a while ago, so the repos can be moved there.

**Comment by esteve** [comment]
@jacobperron I've just moved the repos to ros2-java and added you to the organization, sorry for the long wait.

**Comment by jacobperron** [comment]
Closing this ticket since it is old. We are focused on supporting ROS Galactic now. Please check out the `main` branch :slightly_smiling_face:
