### ISSUE TITLE
Cant find messages

### ISSUE THREAD

**Issue by gambitgeoff** [ros2-java/ros2_java#65]
Hi all,

I'm having the below issue - You'll note the colon in place of the forward slash. Swap the two and the file should exist. I'm trying to track down where this is set. (and learning Python/CMake along the way). :)

Process package 'test_msgs' with context:
--------------------------------------------------------------------------------
 source_space => /home/Development/ros2_java_ws/src/ros2/rcl_interfaces/test_msgs
  build_space => /home/Development/ros2_java_ws/build_isolated/test_msgs
install_space => /home/Development/ros2_java_ws/install_isolated/test_msgs
   make_flags => -j6, -l6
  build_tests => False
--------------------------------------------------------------------------------
+++ Building 'test_msgs'
==> '. /home/Development/ros2_java_ws/build_isolated/test_msgs/cmake__build.sh && /usr/bin/make cmake_check_build_system' in '/home/Development/ros2_java_ws/build_isolated/test_msgs'
-- Found ament_cmake: 0.5.1 (/home/Development/ament_ws/install_isolated/ament_cmake/share/ament_cmake/cmake)
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Override CMake install command with custom implementation using symlinks instead of copying resources
-- Found builtin_interfaces: 0.7.4 (/home/Development/ros2_java_ws/install_isolated/builtin_interfaces/share/builtin_interfaces/cmake)
-- Found rosidl_default_generators: 0.5.0 (/home/Development/ros2_java_ws/install_isolated/rosidl_default_generators/share/rosidl_default_generators/cmake)
-- Found test_interface_files: 0.7.1 (/home/Development/ros2_java_ws/install_isolated/test_interface_files/share/test_interface_files/cmake)
CMake Error at /home/Development/ros2_java_ws/install_isolated/rosidl_cmake/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:70 (message):
  rosidl_generate_interfaces() the passed idl file
  '/home/Development/ros2_java_ws/install_isolated/test_interface_files/share/### test_interface_files:msg/Arrays.msg'
  does not exist
Call Stack (most recent call first):
  CMakeLists.txt:23 (rosidl_generate_interfaces)

**Comment by jacobperron** [comment]
Closing this ticket since it is old. We are focused on supporting ROS Galactic now. Please check out the `main` branch :slightly_smiling_face:
