### ISSUE TITLE
"Built target builtin_interfaces__rosidl_typesupport_introspection_cpp" failed

### ISSUE THREAD

**Issue by dimasoktanugraha** [ros2-java/ros2_java#67]
when i'm in desktop installation at ament build --symlink-install --isolated, i got this error
![Screenshot from 2019-10-08 11-17-46](https://user-images.githubusercontent.com/33495610/66367297-c84b9c80-e9bd-11e9-99a7-e8fcc417ada5.png)

**Comment by charlotteheggem** [comment]
Hi, I have faced a similar problem with "action_msgs__java" instead of "builtin_interfaces__java".
Did you find a solution for this?

**Comment by Jconn** [comment]
I haven't gotten opensplice (or cyclone) to compile when targeting android. Do you get the same issue building with only fastrtps?

**Comment by dimasoktanugraha** [comment]
still don't know how to solve this,

**Comment by charlotteheggem** [comment]
@jacobperron @esteve Do you know what could be wrong?

**Comment by jacobperron** [comment]
@charlotteheggem It sounds related to https://github.com/ros2/ros2/issues/752. If it's the same issue, it was [fixed](https://github.com/ros2/rosidl_typesupport_opensplice/pull/33) in later versions of rosidl_typesupport_opensplice (Crystal onwards). I suspect that since rcljava assumes the ROS 2 Bouncy, it is subsequently not working with newer version of OpenSplice.

**Comment by esteve** [comment]
@charlotteheggem @jacobperron is right about ros2_java assuming Bouncy. Fortunately, he has submitted #66 to update ros2_java to Dashing :-)

**Comment by esteve** [comment]
@Jconn is Android a supported platform for Cyclone? I haven't tested it, though.

**Comment by Jconn** [comment]
cyclone and opensplice failed to build against the android ndk. I moved on to fastRTPS

**Comment by year112** [comment]
you can find rosidl_typesupport_opensplice_cpp/__init__.py
and delete that part
```
else:
        assert False, "Failed to find '// Generated: ' line"
```

**Comment by jacobperron** [comment]
Closing since this is old and we are focused on supporting ROS Galactic. Please checkout the `main` branch :)
