### ISSUE TITLE
Master and dashing don't build

### ISSUE THREAD

**Issue by mhubii** [ros2-java/ros2_java#71]
Hi Steve, and Jacob,

the master branch runs into a missing package

```shell
Process package 'action_msgs' with context:
 source_space => ros2_java/ci-scripts/ros2_java_ws/src/ros2/rcl_interfaces/action_msgs
[...]
CMake Error at CMakeLists.txt:16 (find_package):
  By not providing "Findunique_identifier_msgs.cmake" in CMAKE_MODULE_PATH
  this project has asked CMake to find a package configuration file provided
  by "unique_identifier_msgs", but CMake did not find one.
```

whereas the dashing branch complains about 

```
ros2_java_ws/install_isolated/test_interface_files/share/test_interface_files:msg/Arrays.msg'
  does not exist
```

How to resolve these issues?

Best
Martin

**Comment by mhubii** [comment]
Adding

```
  ros2/unique_identifier_msgs:
    type: git
    url: https://github.com/ros2/unique_identifier_msgs.git
    version: master
```

to ros2_java_desktop.repos resolves it but then another package is missing

```
CMake Error at CMakeLists.txt:21 (find_package):
  By not providing "Findtest_interface_files.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "test_interface_files", but CMake did not find one.
```

However, then the compiler complains that

```
  rosidl_generate_interfaces() the passed idl file
  'ros2_java_ws/src/ros2_java/ci-scripts/output/install_isolated_java/test_interface_files/share/test_interface_files:msg/Arrays.msg'
  does not exist
```

But actually the file sits there as a symbolic link. Anyway, I don't understand why the test_interface_files are required

**Comment by jacobperron** [comment]
The master branch is only compatibility with ROS 2 Bouncy. Are you using Bouncy versions for all ROS 2 packages?

Regarding the dashing branch, it isn't yet fully compatible with Dashing. Only changes for message generation have been merged, I've just opened a PR that should make the `rcljava` package work with Dashing as well (https://github.com/ros2-java/ros2_java/pull/75). I'm still debugging issues related to services though.

**Comment by mhubii** [comment]
thanks for the hint @jacobperron, no I haven't used bouncy so far. I'll try that

**Comment by talregev** [comment]
https://github.com/ros2-java/ros2_java/tree/master/rcljava/src/main/cpp
is not competible with ros dashing. the api was change.

**Comment by jacobperron** [comment]
Please try the `main` branch with ROS Galactic.

Dashing is EOL.
