### ISSUE TITLE
Ros2 Android

### ISSUE THREAD

**Issue by kerliang0801** [ros2-java/ros2_java#89]
Hi! Are there any plans to make ros2_android work as well with any new upcoming ros2 releases?

**Comment by jacobperron** [comment]
I can't speak for @esteve, but I do not have plans (nor the bandwidth) to look at Android.

**Comment by esteve** [comment]
@kerliang0801 the Android-specific parts are really small and well isolated, so there should be no problem supporting it in future releases of ros2-java. In fact, the original goal of ros2-java was to support Android, but it got extended to desktop versions as well.
