### ISSUE TITLE
Compile with colcon

### ISSUE THREAD

**Issue by talregev** [ros2-java/ros2_java#92]
Can you update the document how to compile the code with colocn in dasing branch? 
Thank you.

**Comment by talregev** [comment]
Can you update dashing scripts?
https://github.com/ros2-java/ros2_java/tree/dashing/ci-scripts
That will be with updated android sdk and ndk, also compile with colcon like here?
https://github.com/ros2-java/ros2_java/blob/colcon/ci-scripts/build_java.bash

Thank you.

**Comment by esteve** [comment]
@talregev support for Dashing is underway thanks to @jacobperron and CI is being revamped in https://github.com/ros2-java/ros2_java/pull/96,
